# Generated by Django 2.1.3 on 2018-11-24 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art_Pieces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('art_type', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos/%m/%d/')),
                ('is_Sold', models.BooleanField(default=False)),
                ('date_entered', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.Artist')),
            ],
        ),
    ]
