# Generated by Django 2.1.3 on 2018-11-25 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20181122_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='listing',
            new_name='piece',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='listing_id',
            new_name='piece_id',
        ),
    ]
